src/carts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from carts.views import show_panier, checkout, checkout_done, cart_update

urlpatterns = [
  #  url('^$', courses_grid, name='courses-grid'),
    url('^inscription/(?P<pk>\d+)/$', show_panier, name='show-panier'),
    url('^reserver/(?P<pk>\d+)/$', checkout, name='checkout'),
    url('^confirmation$', checkout_done, name='checkout-done'),
    url(r'^update/$', cart_update, name='update'),
]

src/cours/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from cours.views import detail_cours, courses_list, courses_grid, detail_categorie_grid, detail_categorie_list, detail_sous_categorie_grid, detail_sous_categorie_list
from cours.views import cours_list_formateur, detail_cours_formateur, creer_cours, creer_lecon, edit_lecon, edit_cours, creer_option, edit_option, creer_competence, edit_competence
from cours.views import CreateCoursWizard, FORMS, ajax_get_sous_categories, ajax_get_cours

urlpatterns = [
    url('^(?P<pk>\d+)/$', detail_cours, name='detail-cours'),
  #  url('^$', courses_grid, name='courses-grid'),
    url('^grid/$', courses_grid, name='courses-grid'),
    url('^liste/$', courses_list, name='courses-list'),
    url('^categorie-grid/(?P<pk>\d+)$', detail_categorie_grid, name='categorie-grid'),
    url('^categorie-list/(?P<pk>\d+)$', detail_categorie_list, name='categorie-list'),
    url('^sous-categorie-grid/(?P<pk>\d+)$', detail_sous_categorie_grid, name='sous-categorie-grid'),
    url('^sous-categorie-list/(?P<pk>\d+)$', detail_sous_categorie_list, name='sous-categorie-list'),

    # pour le formateur
    url('^liste-cours-formateur/$', cours_list_formateur, name='cours-liste-formateur'),
    url('^cours-formateur/(?P<pk>\d+)/$', detail_cours_formateur, name='detail-cours-formateur'),
    url('^creer-cours/$', creer_cours, name='creer-cours'),
    url('^edit-cours/(?P<pk>\d+)/$', edit_cours, name='edit-cours'),
    url('^creer-lecon/(?P<pk>\d+)/$', creer_lecon, name='creer-lecon'),
    url('^edit-lecon/(?P<pk>\d+)/$', edit_lecon, name='edit-lecon'),
    url('^creer-option/(?P<pk>\d+)/$', creer_option, name='creer-option'),
    url('^edit-option/(?P<pk>\d+)/$', edit_option, name='edit-option'),
    url('^creer-competence/(?P<pk>\d+)/$', creer_competence, name='creer-competence'),
    url('^edit-competence/(?P<pk>\d+)/$', edit_competence, name='edit-competence'),

    url('^creer-cours/$', CreateCoursWizard.as_view(FORMS), name="creer-cours"),
    url('^get_sous_categories/(?P<pk>\d+)/$', ajax_get_sous_categories, name="get-sous-categories"),
    url('^ajax-get-cours/$', ajax_get_cours, name="ajax-get-cours"),
]

src/cours/models.py
from django.db import models
from fontawesome.fields import IconField
from django.db.models.signals import pre_save, post_save, post_delete
from django.contrib.auth.models import User
from partenaires.models import SalleCours
from django.urls import reverse

class Categorie(models.Model):
    nom  = models.CharField(max_length = 200)
    icon = IconField()
    image = models.ImageField(upload_to = 'mes_images/', blank=True, null=True)

    def __str__(self):
        return self.nom

    def get_number_cours(self):
        souscategorie_ids = self.souscategorie_set.all().values_list('id', flat=True)
        cours = SousCategorieCours.objects.filter(sous_categorie__id__in = souscategorie_ids).values_list('cours', flat=True)
        return len(set(cours))

    def get_cours(self):
        souscategorie_ids = self.souscategorie_set.all().values_list('id', flat=True)
        cours_ids = SousCategorieCours.objects.filter(sous_categorie__id__in = souscategorie_ids).values_list('cours', flat=True)
        cours = Cours.objects.filter(id__in = cours_ids)
        return set(cours)

class SousCategorie(models.Model):
    nom       = models.CharField(max_length = 200)
    icon      = IconField()
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE,)

    def __str__(self):
        return self.nom

    def get_cours(self):
        cours_ids = SousCategorieCours.objects.filter(sous_categorie=self).values_list('cours', flat=True)
        cours = Cours.objects.filter(id__in = cours_ids)
        return set(cours)

class CoursQuerySet(models.query.QuerySet):
    def validated(self):
        return self.filter(validated=True)

class CoursManager(models.Manager):

    def get_queryset(self):
        return CoursQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().validated()

ANNEES = (
          ('ba1', 'BA1'),
          ('ba2', 'BA2'),
          ('ba3', 'BA3'),
          ('ma1', 'MA1'),
          ('ma2', 'MA2'),
)
class Cours(models.Model):
    titre              = models.CharField(max_length = 500)
    courte_description = models.TextField(blank = True, null = True)
    long_description   = models.TextField(blank = True, null = True)
    prerequis          = models.TextField(blank=True, null=True)
    image              = models.ImageField(upload_to = 'mes_images/')
    active             = models.BooleanField(default = True)
    total              = models.CharField(max_length=20, default="0")
    validated          = models.BooleanField(default = False)
    moyenne_review     = models.CharField(max_length=20, default="5")
    faculte            = models.ForeignKey('apprenants.Faculte', on_delete=models.CASCADE,blank = True, null = True)
    universite         = models.ForeignKey('apprenants.University', on_delete=models.CASCADE,blank = True, null = True)
    annee              = models.CharField(max_length=20, blank = True, null = True, choices=ANNEES)

    objects = CoursManager()
    def __str__(self):
        return self.titre

    def get_teachers(self):
        return set(self.formateurcours_set.all())

    def get_absolute_url(self):
        #return "/detail-cours/pk/"
        return reverse("detail-cours", kwargs={'pk': self.pk})

    def get_locations(self):
        lecons_pks = self.get_lecons().values_list('pk', flat=True)
        salles_pks = Option.objects.filter(lecon__pk__in = lecons_pks).values_list('salle', flat=True)
        salles = SalleCours.objects.filter(pk__in = salles_pks)
        return salles


    def get_related(self):
        cours_related_ids = []
        sous_categories =  self.get_sous_categories()
        for ss_c in sous_categories:
            ss_cat_cours = SousCategorieCours.objects.filter(sous_categorie = ss_c)
            cours_ids = ss_cat_cours.values_list('cours', flat=True)
            for c_id in cours_ids:
              cours_related_ids.append(c_id)
        cours_related = Cours.objects.filter(pk__in=cours_related_ids).exclude(pk = self.pk)
        print(cours_related)
        return cours_related

    def get_main_teacher(self):
        main_teachers = self.formateurcours_set.filter(main=True)
        if len(main_teachers) > 0:
            main_teacher = main_teachers.first()
            teacher = main_teacher.formateur
            return teacher
        else :
            main_teachers = self.formateurcours_set.all()
            main_teacher = main_teachers.first()
            teacher = main_teacher.formateur
            return teacher

    def get_lecons(self):
        lecons = Lecon.objects.filter(cours=self)
        return lecons

    def get_sous_categories(self):
        souscategoriecours = SousCategorieCours.objects.filter(cours=self)
        sous_categorie_ids = souscategoriecours.values_list('sous_categorie', flat=True)
        sous_categories = SousCategorie.objects.filter(pk__in=sous_categorie_ids)
        return set(sous_categories)

    def total_time_lecons(self):
        total = 0
        for lecon in self.get_lecons():
            total += lecon.get_time_lecon()
        return round(total, 2)

    def get_capacite(self):
        lecon = self.get_lecons().first()
        option = lecon.option_set.all()
        capacite = option.first().capacite
        return capacite

    def get_moyenne_review(self):
        return float(self.moyenne_review)

    def get_one_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=1)
    def get_two_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=2)
    def get_three_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=3)
    def get_four_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=4)
    def get_five_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=5)

    def get_one_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=1))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_two_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=2))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_three_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=3))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_four_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=4))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_five_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=5))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0

class FormateurCours(models.Model):
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE,)
    formateur = models.ForeignKey('formateurs.Formateur', on_delete=models.CASCADE,)
    main = models.BooleanField(default = True)
    def __str__(self):
        return self.cours.titre + ' - ' + self.formateur.email
class SousCategorieCours(models.Model):
    sous_categorie = models.ForeignKey(SousCategorie, on_delete=models.CASCADE,)
    cours          = models.ForeignKey(Cours, on_delete=models.CASCADE,)

    def __str__(self):
        return self.sous_categorie.nom + ' - ' + self.cours.titre

class SkillCours(models.Model):
    skill = models.TextField(blank=True, null=True)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE,)

    def __str__(self):
        return self.skill[:15] + ' - ' + self.cours.titre

class Lecon(models.Model):
    titre     = models.CharField(max_length = 500, blank = True, null = True)
    cours     = models.ForeignKey(Cours, on_delete=models.CASCADE,)
    contenu   = models.TextField(blank=True, null=True)
    ordre     = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.cours.titre + ' - ' + self.contenu[:30]
    class Meta:
        ordering = ('ordre', )

    def get_time_lecon(self):
        options = Option.objects.filter(lecon=self)
        if len(options)>0:
            option = options.first()
            delta = option.fin - option.debut
            delta_hours = delta.total_seconds()/3600
            return round(delta_hours, 2)
        else :
          return 0

class Option(models.Model):
    lecon    = models.ForeignKey(Lecon, on_delete=models.CASCADE, blank=True, null=True)
    debut    = models.DateTimeField()
    fin      = models.DateTimeField()
    tarif    = models.CharField(max_length=10)
    capacite = models.PositiveSmallIntegerField(default=3)
    salle    = models.ForeignKey('partenaires.SalleCours', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.lecon:
            return self.lecon.cours.titre + " - " + self.debut.strftime("%d/%m/%Y, %H:%M")
        else :
            return "Lecon - " + self.debut.strftime("%d/%m/%Y, %H:%M")
    class Meta:
        ordering = ('debut', )
    def show_date_range(self):
        date_debut  = self.debut.strftime("%d/%m/%Y")
        date_fin    = self.fin.strftime("%d/%m/%Y")
        heure_debut = self.debut.strftime("%H:%M")
        heure_fin   = self.fin.strftime("%H:%M")
        if date_debut == date_fin:
            return "Le {} de {} à {}".format(date_debut, heure_debut, heure_fin)
        else :
            return "Du {} ({}) au {} ({})".format(date_debut, heure_debut, date_fin, heure_fin)

def option_post_save(sender, instance, *args, **kwargs):

src/cours/templates/cours/mes-cours/cours-detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}


{% block content %}

  <main>
    <section id="hero_in" class="courses" style="background-image: url({{ cours.image.url }});">
      <div class="wrapper">
        <div class="container">
          <h1 class="fadeInUp"><span></span>{{ cours.titre }}</h1>
        </div>
      </div>
    </section>
    <!--/hero_in-->

    <div class="bg_color_1">
      <nav class="secondary_nav sticky_horizontal">
        <div class="container">
          <ul class="clearfix">
            <li><a href="#description" class="active">Description</a></li>
            <li><a href="#lessons">Cours</a></li>
            <li><a href="#reviews">Feedbacks</a></li>
          </ul>
        </div>
      </nav>
      <div class="container margin_60_35">
        <div class="row">
          <div class="col-lg-8">

            <section id="description">
              <h2>Description <a href="{% url 'edit-cours' pk=cours.pk %}" class="edit-link" style="display:inline;font-size:15px;"><i class="icon-edit-2"></i> Modifier</a></h2>

              {% autoescape off %}{{ cours.long_description }}{% endautoescape %}
              <ul class="list_ok">
                {% for skill in cours.skillcours_set.all %}
                <li>
                  <h6>{% autoescape off %}{{ skill.skill }} (<a href="{% url 'edit-competence' pk=skill.pk %}"><i class="icon-edit-2"></i> Modifier</a>){% endautoescape %}</h6>
                </li>
                {% endfor %}
              </ul>
              <a href="{% url 'creer-competence' pk=cours.pk %}" class="btn_1">Ajouter une compétence</a>
              <hr>
              <p>Mea appareat omittantur eloquentiam ad, nam ei quas oportere democritum. Prima causae admodum id est, ei timeam inimicus sed. Sit an meis aliquam, cetero inermis vel ut. An sit illum euismod facilisis, tamquam vulputate pertinacia eum at.</p>
              <div class="row">
                <div class="col-lg-6">
                  <ul class="bullets">
                    <li>Dolorem mediocritatem</li>
                    <li>Mea appareat</li>
                    <li>Prima causae</li>
                    <li>Singulis indoctum</li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="bullets">
                    <li>Timeam inimicus</li>
                    <li>Oportere democritum</li>
                    <li>Cetero inermis</li>
                    <li>Pertinacia eum</li>
                  </ul>
                </div>
              </div>
              <!-- /row -->
            </section>
            <!-- /section -->

            <section id="lessons">
              <div class="intro_title">
                <h2>Leçons</h2>
                <ul>
                  <li>{{cours.lecon_set.all|length }} leçons</li>
                </ul>
              </div>
              <div id="accordion_lessons" role="tablist" class="add_bottom_45">
                {% for lecon in cours.lecon_set.all %}
                <div class="card">
                  <div class="card-header" role="tab" id="heading{{lecon.pk}}">
                    <h5 class="mb-0">
                      {% if forloop.first %}
                      <div data-toggle="collapse" href="#collapse{{lecon.pk}}" aria-expanded="true" aria-controls="collapse{{lecon.pk}}">
                        <i class="indicator ti-minus blue-icon"></i> {{ lecon.titre }}
                        <div style="display:inline;" class="edit-link">
                          <a href="{% url 'edit-lecon' pk=lecon.pk %}"  style="display:inline;"><i class="icon-edit-2"></i> Modifier</a>
                          <a href="{% url 'creer-option' pk=lecon.pk %}" style="display:inline;"><i class="icon-plus-squared-small"></i> Ajouter une date</a>
                        </div>
                      </div>
                      {% else %}
                      <div class="collapsed" data-toggle="collapse" href="#collapse{{lecon.pk}}" aria-expanded="false" aria-controls="#collapse{{lecon.pk}}">
                        <i class="indicator ti-plus blue-icon"></i> {{ lecon.titre }}
                        <div style="display:inline;" class="edit-link">
                          <a href="{% url 'edit-lecon' pk=lecon.pk %}"  style="display:inline;"><i class="icon-edit-2"></i> Modifier</a>
                          <a href="{% url 'creer-option' pk=lecon.pk %}" style="display:inline;"><i class="icon-plus-squared-small"></i> Ajouter une date</a>
                        </div>
                      </div>
                      {% endif %}
                    </h5>
                  </div>

                  <div id="collapse{{lecon.pk}}" class="collapse {% if forloop.first %}show {% endif %}" role="tabpanel" aria-labelledby="heading{{lecon.pk}}" data-parent="#accordion_lessons">
                    <div class="card-body">
                      <div class="list_lessons">
                        {% autoescape off %}{{ lecon.contenu }}{% endautoescape %}
                        {% if lecon.option_set.all|length > 1 %}
                            <p>Choisis l'horaire qui te convient le mieux : </p>
                        {% endif %}
                        <ul>
                          {% for option in lecon.option_set.all %}
                          <li><a href="" class="video">{{ option.show_date_range }}</a><span>{{ option.tarif }} &euro; /<a href="{% url 'edit-option' pk=option.pk %}"><i class="icon-edit-2"></i>Modifier</a></span></li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /card -->
                {% endfor %}
                <a href="{% url 'creer-lecon' pk=cours.pk %}" class="btn_1">Ajouter une leçon</a>
              </div>
              <!-- /accordion -->
            </section>
            <!-- /section -->

            <section id="reviews">
              <h2>Feedbacks</h2>
              <div class="reviews-container">
                <div class="row">
                  <div class="col-lg-3">
                    <div id="review_summary">
                      <strong>4.7</strong>
                      <div class="rating">
                        <i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
                      </div>
                      <small>basé sur {{ cours.reviewcours_set.all|length }} feedbacks</small>
                    </div>
                  </div>
                  <div class="col-lg-9">
                    <div class="row">
                      <div class="col-lg-10 col-9">
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                      <div class="col-lg-2 col-3"><small><strong>5 stars</strong></small></div>
                    </div>
                    <!-- /row -->
                    <div class="row">
                      <div class="col-lg-10 col-9">
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                      <div class="col-lg-2 col-3"><small><strong>4 stars</strong></small></div>
                    </div>
                    <!-- /row -->
                    <div class="row">
                      <div class="col-lg-10 col-9">
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                      <div class="col-lg-2 col-3"><small><strong>3 stars</strong></small></div>
                    </div>
                    <!-- /row -->
                    <div class="row">
                      <div class="col-lg-10 col-9">
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                      <div class="col-lg-2 col-3"><small><strong>2 stars</strong></small></div>
                    </div>
                    <!-- /row -->
                    <div class="row">
                      <div class="col-lg-10 col-9">
                        <div class="progress">
                          <div class="progress-bar" role="progressbar" style="width: 0" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                      <div class="col-lg-2 col-3"><small><strong>1 stars</strong></small></div>
                    </div>
                    <!-- /row -->
                  </div>
                </div>
                <!-- /row -->
              </div>

              <hr>

              <div class="reviews-container">
                {% for review in cours.reviewcours_set.all %}
                <div class="review-box clearfix">
                  <figure class="rev-thumb"><img src="http://via.placeholder.com/150x150/ccc/fff/avatar1.jpg" alt="">
                  </figure>
                  <div class="rev-content">
                    <div class="rating">
                      <i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
                    </div>
                    <div class="rev-info">
                      {{ review.auteur.username }} – {{review.created}}:
                    </div>
                    <div class="rev-text">
                      <p>
                        {{ review.commentaire }}
                      </p>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
              <!-- /review-container -->
            </section>
            <!-- /section -->
          </div>
          <!-- /col -->

          <aside class="col-lg-4" id="sidebar">
            <div class="box_detail">
              <figure>
                <a href="https://www.youtube.com/watch?v=LDgd_gUcqCw" class="video"><i class="arrow_triangle-right"></i><img src="http://via.placeholder.com/800x533/ccc/fff/course_1.jpg" alt="" class="img-fluid"><span>View course preview</span></a>
              </figure>
              <div class="price">
                {{ cours.total }} &euro;<span class="original_price"><em>$49</em>60% discount price</span>
              </div>
              <a href="#0" class="btn_1 full-width">Purchase</a>
              <a href="#0" class="btn_1 full-width outline"><i class="icon_heart"></i> Add to wishlist</a>
              <div id="list_feat">
                <h3>What's includes</h3>
                <ul>
                  <li><i class="icon_mobile"></i>Mobile support</li>
                  <li><i class="icon_archive_alt"></i>Lesson archive</li>
                  <li><i class="icon_mobile"></i>Mobile support</li>
                  <li><i class="icon_chat_alt"></i>Tutor chat</li>
                  <li><i class="icon_document_alt"></i>Course certificate</li>
                </ul>
              </div>
            </div>
          </aside>
        </div>
        <!-- /row -->
      </div>
      <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
  </main>
  <!--/main-->

{% endblock %}

src/cours/templates/cours/mes-cours/cours-list.html
{% extends "formateurs/base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block head_title %}
{% endblock %}

{% block base_head %}
<script src="{% static 'js/tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tinymce/custom.js' %}" ></script>
{% endblock %}

{% block content %}
  <!-- /Navigation-->
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Créer un cours</li>
      </ol>
    <div class="box_general">
      <div class="header_box">
        <h2 class="d-inline-block">Tes cours</h2>
        <div class="filter">
          <select name="orderby" class="selectbox">
            <option value="Any status">Any status</option>
            <option value="Approved">Started</option>
            <option value="Pending">Pending</option>
            <option value="Cancelled">Cancelled</option>
          </select>
        </div>
      </div>
      <div class="list_general">
        <ul>
          {% for c in request.user.formateur.formateurcours_set.all %}
          <p></p>
          <li>
            <figure><img src="{{ c.cours.image.url }}" alt=""></figure>
            <h4>{{ c.cours.titre }} <i class="pending">Pending</i></h4>
            <ul class="course_list">
              <li><strong>Début</strong> 11 November 2017</li>
              <li><strong>Fin</strong> 11 April 2018</li>
              <li><strong>Catégorie</strong> Science, Economy</li>
              <li><strong>Professeur</strong> Mark Twain</li>
            </ul>
            <h6>Description du cours</h6>
           {% autoescape off %}{{ c.cours.courte_description }} {% endautoescape %}
            <ul class="buttons">
              <li><a href="#0" class="btn_1 gray approve"><i class="fa fa-fw fa-check-circle-o"></i> Approve</a></li>
              <li><a href="#0" class="btn_1 gray delete"><i class="fa fa-fw fa-times-circle-o"></i> Cancel</a></li>
              <li><a href="{% url 'detail-cours-formateur' pk=c.cours.pk %}" class="btn_1 gray delete"><i class="fa fa-fw fa-times-circle-o"></i> Voir</a></li>
              <li><a href="{% url 'edit-cours' pk=c.cours.pk %}" class="btn_1 gray delete"><i class="fa fa-fw fa-times-circle-o"></i> Modifier</a></li>
            </ul>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <!-- /box_general-->
    <nav aria-label="...">
      <ul class="pagination pagination-sm add_bottom_30">
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">Next</a>
        </li>
      </ul>
    </nav>
    <!-- /row-->
    </div>
    <!-- /.container-fluid-->
  </div>
  <!-- /.container-wrapper-->
{% endblock %}

{% block javascript %}
{% endblock %}

src/cours/templates/cours/mes-cours/creer-cours.html
{% extends "formateurs/base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block head_title %}
{% endblock %}

{% block base_head %}
<script src="{% static 'js/tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tinymce/custom.js' %}" ></script>
{% endblock %}

{% block content %}
  <!-- /Navigation-->
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Créer un cours</li>
      </ol>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2><i class="fa fa-user"></i>Profile details</h2>
      </div>


      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
          <label>Your photo</label>
            <form action="/file-upload" class="dropzone"></form>
            </div>
        </div>
        <div class="col-md-8 add_top_30">
          <form method="post" enctype="multipart/form-data">{% csrf_token %}
              {% crispy form %}
          </form>
        </div>
      </div>
    </div>
    <!-- /box_general-->
    <div class="row">
      <div class="col-md-6">
        <div class="box_general padding_bottom">
          <div class="header_box version_2">
            <h2><i class="fa fa-lock"></i>Change password</h2>
          </div>
          <div class="form-group">
            <label>Old password</label>
            <input class="form-control" type="password">
          </div>
          <div class="form-group">
            <label>New password</label>
            <input class="form-control" type="password">
          </div>
          <div class="form-group">
            <label>Confirm new password</label>
            <input class="form-control" type="password">
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="box_general padding_bottom">
          <div class="header_box version_2">
            <h2><i class="fa fa-envelope"></i>Change email</h2>
          </div>
          <div class="form-group">
            <label>Old email</label>
            <input class="form-control" name="old_email" id="old_email" type="email">
          </div>
          <div class="form-group">
            <label>New email</label>
            <input class="form-control" name="new_email" id="new_email" type="email">
          </div>
          <div class="form-group">
            <label>Confirm new email</label>
            <input class="form-control" name="confirm_new_email" id="confirm_new_email" type="email">
          </div>
        </div>
      </div>
    </div>
    <!-- /row-->
    <p><a href="#0" class="btn_1 medium">Confirmer</a></p>
    </div>
    <!-- /.container-fluid-->
    </div>
    <!-- /.container-wrapper-->
{% endblock %}

{% block javascript %}
{% endblock %}