src/carts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from carts.views import show_panier, checkout, checkout_done, cart_update

urlpatterns = [
  #  url('^$', courses_grid, name='courses-grid'),
    url('^inscription/(?P<pk>\d+)/$', show_panier, name='show-panier'),
    url('^reserver/(?P<pk>\d+)/$', checkout, name='checkout'),
    url('^confirmation$', checkout_done, name='checkout-done'),
    url(r'^update/$', cart_update, name='update'),
]

src/cours/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from cours.views import detail_cours, courses_list, courses_grid, detail_categorie_grid, detail_categorie_list, detail_sous_categorie_grid, detail_sous_categorie_list
from cours.views import cours_list_formateur, detail_cours_formateur, creer_cours, creer_lecon, edit_lecon, edit_cours, creer_option, edit_option, creer_competence, edit_competence
from cours.views import CreateCoursWizard, FORMS, ajax_get_sous_categories, ajax_get_cours

urlpatterns = [
    url('^(?P<pk>\d+)/$', detail_cours, name='detail-cours'),
  #  url('^$', courses_grid, name='courses-grid'),
    url('^grid/$', courses_grid, name='courses-grid'),
    url('^liste/$', courses_list, name='courses-list'),
    url('^categorie-grid/(?P<pk>\d+)$', detail_categorie_grid, name='categorie-grid'),
    url('^categorie-list/(?P<pk>\d+)$', detail_categorie_list, name='categorie-list'),
    url('^sous-categorie-grid/(?P<pk>\d+)$', detail_sous_categorie_grid, name='sous-categorie-grid'),
    url('^sous-categorie-list/(?P<pk>\d+)$', detail_sous_categorie_list, name='sous-categorie-list'),

    # pour le formateur
    url('^liste-cours-formateur/$', cours_list_formateur, name='cours-liste-formateur'),
    url('^cours-formateur/(?P<pk>\d+)/$', detail_cours_formateur, name='detail-cours-formateur'),
    url('^creer-cours/$', creer_cours, name='creer-cours'),
    url('^edit-cours/(?P<pk>\d+)/$', edit_cours, name='edit-cours'),
    url('^creer-lecon/(?P<pk>\d+)/$', creer_lecon, name='creer-lecon'),
    url('^edit-lecon/(?P<pk>\d+)/$', edit_lecon, name='edit-lecon'),
    url('^creer-option/(?P<pk>\d+)/$', creer_option, name='creer-option'),
    url('^edit-option/(?P<pk>\d+)/$', edit_option, name='edit-option'),
    url('^creer-competence/(?P<pk>\d+)/$', creer_competence, name='creer-competence'),
    url('^edit-competence/(?P<pk>\d+)/$', edit_competence, name='edit-competence'),

    url('^creer-cours/$', CreateCoursWizard.as_view(FORMS), name="creer-cours"),
    url('^get_sous_categories/(?P<pk>\d+)/$', ajax_get_sous_categories, name="get-sous-categories"),
    url('^ajax-get-cours/$', ajax_get_cours, name="ajax-get-cours"),
]

src/cours/models.py
from django.db import models
from fontawesome.fields import IconField
from django.db.models.signals import pre_save, post_save, post_delete
from django.contrib.auth.models import User
from partenaires.models import SalleCours
from django.urls import reverse

class Categorie(models.Model):
    nom  = models.CharField(max_length = 200)
    icon = IconField()
    image = models.ImageField(upload_to = 'mes_images/', blank=True, null=True)

    def __str__(self):
        return self.nom

    def get_number_cours(self):
        souscategorie_ids = self.souscategorie_set.all().values_list('id', flat=True)
        cours = SousCategorieCours.objects.filter(sous_categorie__id__in = souscategorie_ids).values_list('cours', flat=True)
        return len(set(cours))

    def get_cours(self):
        souscategorie_ids = self.souscategorie_set.all().values_list('id', flat=True)
        cours_ids = SousCategorieCours.objects.filter(sous_categorie__id__in = souscategorie_ids).values_list('cours', flat=True)
        cours = Cours.objects.filter(id__in = cours_ids)
        return set(cours)

class SousCategorie(models.Model):
    nom       = models.CharField(max_length = 200)
    icon      = IconField()
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE,)

    def __str__(self):
        return self.nom

    def get_cours(self):
        cours_ids = SousCategorieCours.objects.filter(sous_categorie=self).values_list('cours', flat=True)
        cours = Cours.objects.filter(id__in = cours_ids)
        return set(cours)

class CoursQuerySet(models.query.QuerySet):
    def validated(self):
        return self.filter(validated=True)

class CoursManager(models.Manager):

    def get_queryset(self):
        return CoursQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().validated()

ANNEES = (
          ('ba1', 'BA1'),
          ('ba2', 'BA2'),
          ('ba3', 'BA3'),
          ('ma1', 'MA1'),
          ('ma2', 'MA2'),
)
class Cours(models.Model):
    titre              = models.CharField(max_length = 500)
    courte_description = models.TextField(blank = True, null = True)
    long_description   = models.TextField(blank = True, null = True)
    prerequis          = models.TextField(blank=True, null=True)
    image              = models.ImageField(upload_to = 'mes_images/')
    active             = models.BooleanField(default = True)
    total              = models.CharField(max_length=20, default="0")
    validated          = models.BooleanField(default = False)
    moyenne_review     = models.CharField(max_length=20, default="5")
    faculte            = models.ForeignKey('apprenants.Faculte', on_delete=models.CASCADE,blank = True, null = True)
    universite         = models.ForeignKey('apprenants.University', on_delete=models.CASCADE,blank = True, null = True)
    annee              = models.CharField(max_length=20, blank = True, null = True, choices=ANNEES)

    objects = CoursManager()
    def __str__(self):
        return self.titre

    def get_teachers(self):
        return set(self.formateurcours_set.all())

    def get_absolute_url(self):
        #return "/detail-cours/pk/"
        return reverse("detail-cours", kwargs={'pk': self.pk})

    def get_locations(self):
        lecons_pks = self.get_lecons().values_list('pk', flat=True)
        salles_pks = Option.objects.filter(lecon__pk__in = lecons_pks).values_list('salle', flat=True)
        salles = SalleCours.objects.filter(pk__in = salles_pks)
        return salles


    def get_related(self):
        cours_related_ids = []
        sous_categories =  self.get_sous_categories()
        for ss_c in sous_categories:
            ss_cat_cours = SousCategorieCours.objects.filter(sous_categorie = ss_c)
            cours_ids = ss_cat_cours.values_list('cours', flat=True)
            for c_id in cours_ids:
              cours_related_ids.append(c_id)
        cours_related = Cours.objects.filter(pk__in=cours_related_ids).exclude(pk = self.pk)
        print(cours_related)
        return cours_related

    def get_main_teacher(self):
        main_teachers = self.formateurcours_set.filter(main=True)
        if len(main_teachers) > 0:
            main_teacher = main_teachers.first()
            teacher = main_teacher.formateur
            return teacher
        else :
            main_teachers = self.formateurcours_set.all()
            main_teacher = main_teachers.first()
            teacher = main_teacher.formateur
            return teacher

    def get_lecons(self):
        lecons = Lecon.objects.filter(cours=self)
        return lecons

    def get_sous_categories(self):
        souscategoriecours = SousCategorieCours.objects.filter(cours=self)
        sous_categorie_ids = souscategoriecours.values_list('sous_categorie', flat=True)
        sous_categories = SousCategorie.objects.filter(pk__in=sous_categorie_ids)
        return set(sous_categories)

    def total_time_lecons(self):
        total = 0
        for lecon in self.get_lecons():
            total += lecon.get_time_lecon()
        return round(total, 2)

    def get_capacite(self):
        lecon = self.get_lecons().first()
        option = lecon.option_set.all()
        capacite = option.first().capacite
        return capacite

    def get_moyenne_review(self):
        return float(self.moyenne_review)

    def get_one_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=1)
    def get_two_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=2)
    def get_three_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=3)
    def get_four_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=4)
    def get_five_star_review(self):
        return ReviewCours.objects.filter(cours=self, rating=5)

    def get_one_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=1))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_two_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=2))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_three_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=3))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_four_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=4))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0
    def get_five_star_review_percentage(self):
        if len(ReviewCours.objects.filter(cours=self))>0:
            return int(100*(len(ReviewCours.objects.filter(cours=self, rating=5))/len(ReviewCours.objects.filter(cours=self))))
        else :
            return 0

class FormateurCours(models.Model):
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE,)
    formateur = models.ForeignKey('formateurs.Formateur', on_delete=models.CASCADE,)
    main = models.BooleanField(default = True)
    def __str__(self):
        return self.cours.titre + ' - ' + self.formateur.email
class SousCategorieCours(models.Model):
    sous_categorie = models.ForeignKey(SousCategorie, on_delete=models.CASCADE,)
    cours          = models.ForeignKey(Cours, on_delete=models.CASCADE,)

    def __str__(self):
        return self.sous_categorie.nom + ' - ' + self.cours.titre

class SkillCours(models.Model):
    skill = models.TextField(blank=True, null=True)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE,)

    def __str__(self):
        return self.skill[:15] + ' - ' + self.cours.titre

class Lecon(models.Model):
    titre     = models.CharField(max_length = 500, blank = True, null = True)
    cours     = models.ForeignKey(Cours, on_delete=models.CASCADE,)
    contenu   = models.TextField(blank=True, null=True)
    ordre     = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.cours.titre + ' - ' + self.contenu[:30]
    class Meta:
        ordering = ('ordre', )

    def get_time_lecon(self):
        options = Option.objects.filter(lecon=self)
        if len(options)>0:
            option = options.first()
            delta = option.fin - option.debut
            delta_hours = delta.total_seconds()/3600
            return round(delta_hours, 2)
        else :
          return 0

class Option(models.Model):
    lecon    = models.ForeignKey(Lecon, on_delete=models.CASCADE, blank=True, null=True)
    debut    = models.DateTimeField()
    fin      = models.DateTimeField()
    tarif    = models.CharField(max_length=10)
    capacite = models.PositiveSmallIntegerField(default=3)
    salle    = models.ForeignKey('partenaires.SalleCours', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.lecon:
            return self.lecon.cours.titre + " - " + self.debut.strftime("%d/%m/%Y, %H:%M")
        else :
            return "Lecon - " + self.debut.strftime("%d/%m/%Y, %H:%M")
    class Meta:
        ordering = ('debut', )
    def show_date_range(self):
        date_debut  = self.debut.strftime("%d/%m/%Y")
        date_fin    = self.fin.strftime("%d/%m/%Y")
        heure_debut = self.debut.strftime("%H:%M")
        heure_fin   = self.fin.strftime("%H:%M")
        if date_debut == date_fin:
            return "Le {} de {} à {}".format(date_debut, heure_debut, heure_fin)
        else :
            return "Du {} ({}) au {} ({})".format(date_debut, heure_debut, date_fin, heure_fin)

def option_post_save(sender, instance, *args, **kwargs):

src/cours/templates/cours/courses-grid-sidebar.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block head_title %}{% endblock %}


{% block content %}

  <main>
    <section id="hero_in" class="courses">
      <div class="wrapper">
        <div class="container">
          <h1 class="fadeInUp"><span></span>Nos cours</h1>
        </div>
      </div>
    </section>
    <!--/hero_in-->

    <div class="filters_listing sticky_horizontal" >
      <div class="container">
        <ul class="clearfix">
          <li>
            <div class="switch-field">
              <input type="radio" id="all" name="listing_filter" value="all" checked>
              <label for="all">Tout</label>
              <input type="radio" id="popular" name="listing_filter" value="popular">
              <label for="popular">Populaire</label>
              <input type="radio" id="latest" name="listing_filter" value="latest">
              <label for="latest">Récent</label>
            </div>
          </li>
          <li>
            <div class="layout_view">
              <a href="#0" class="active"><i class="icon-th"></i></a>
              <a href="{% url 'courses-list' %}"><i class="icon-th-list"></i></a>
            </div>
          </li>
          <li>
            <select name="orderby" class="selectbox" onchange="location = this.value;">
              <option value="category">Categories</option>
              <option value="all">Tout</option>
              {% for categorie in categories %}
              <option value="{% url 'categorie-grid' pk=categorie.pk %}">{{ categorie.nom }}</option>
              {% endfor %}
              </select>
          </li>
        </ul>
      </div>
      <!-- /container -->
    </div>
    <!-- /filters -->

    <div class="container margin_60_35" id="courses">
      <div class="row">
        <aside class="col-lg-3" id="sidebar">
          <div id="filters_col"> <a data-toggle="collapse" href="#collapseFilters" aria-expanded="false" aria-controls="collapseFilters" id="filters_col_bt">Filters </a>
            <div class="collapse show" id="collapseFilters">
              <div class="filter_type">
                <form method="POST" enctype="multipart/form-data" class="search-form">{% csrf_token %}
                    {% crispy form %}
                </form>
              </div>
            </div>
            <!--/collapse -->
          </div>
          <!--/filters col-->
        </aside>
        <!-- /aside -->

        <div class="col-lg-9">
          <div class="row replace" style="display:flex;">
            {% if cours|length > 0%}
              {% for c in cours %}
              <div class="col-md-6" style="display:flex;">
                {% include 'cours/snippets/card-cours-grid.html' with instance=c %}
              </div>
              <!-- /box_grid -->
              {% endfor %}
            {% else %}
              <div class="col-md-6" style="display:flex;">
                <p>Aucun résultat ne correspond à votre recherche.</p>
              </div>
            {% endif %}
          </div>
          <!-- /row -->
          <p class="text-center"><a href="#0" class="btn_1 rounded add_top_30">Charger plus</a></p>
        </div>
        <!-- /col -->
      </div>
      <!-- /row -->
    </div>

    <!-- /container -->
    <div class="bg_color_1">
      <div class="container margin_60_35">
        <div class="row">
          <div class="col-md-4">
            <a href="{% url 'contact' %}" class="boxed_list">
              <i class="pe-7s-help2"></i>
              <h4>Besoin d'aide? Contacte-nous</h4>
              <p>Cum appareat maiestatis interpretaris et, et sit.</p>
            </a>
          </div>
          <div class="col-md-4">
            <a href="#0" class="boxed_list">
              <i class="pe-7s-wallet"></i>
              <h4>Paiements et remboursements</h4>
              <p>Qui ea nemore eruditi, magna prima possit eu mei.</p>
            </a>
          </div>
          <div class="col-md-4">
            <a href="#0" class="boxed_list">
              <i class="pe-7s-note2"></i>
              <h4>Qualité assurée</h4>
              <p>Hinc vituperata sed ut, pro laudem nonumes ex.</p>
            </a>
          </div>
        </div>
        <!-- /row -->
      </div>
      <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
  </main>
  <!--/main-->


{% endblock %}

{% block javascript %}
<script>
$(function () {
    {% if anchor %}
        console.log("ancre repérée")
        $(document).ready(function(){
            window.location = '#{{ anchor }}'
        });
        $(document.body).animate({

            'scrollTop':   $('#{{ anchor }}').offset().top
        }, 2000);
    {% endif %}
});

  function display_facultes(){
            var universite_id = $('#id_universite :selected').val();
            $('#div_id_faculte').show()
            request_url = '/apprenants/get_faculte/' + universite_id + '/';
            $.ajax({
                  url: request_url,
                  success: function(json){
                    var strResult;
                    $('#div_id_faculte').empty();
                    strResult = '<label for="id_faculte" class="control-label">'+
                      'Faculté </label><br>'+
                      '<select name="faculte" class="select form-control" required="" id="id_faculte">'+
                      '<option value="" selected="">---------</option>'

                      for(var j = 0; j < json.length; j++){
                            strResult += '<option value="' + parseInt(json[j][0]) + '">' + json[j][1] +'</option>'
                        }
                        strResult += '</select>'
                        $('#div_id_faculte').append(strResult)
                  }
            })
  }

  if ($('#id_universite').value){
    display_facultes();
  }
  $('#id_universite').change(function() {
    display_facultes();
  });


  var searchForm = $(".search-form")
  var httpMethod = searchForm.attr("method");
  var actionEndpoint = '/cours/ajax-get-cours/';

  function ajax_display_cours() {
      var formData = searchForm.serialize();
      console.log(formData)
      $.ajax({
        url: actionEndpoint,
        method: httpMethod,
        data: formData,
        success: function(data){
            $('.replace').html(data.cours_html)
        },
        error: function(errorData){
          $.alert({
            title: "Oops!",
            content: "Une erreur s'est produite.",
            theme: "modern",
          })
        }
      })
    }

  searchForm.change(function() {
      ajax_display_cours()
  });
</script>


{% endblock %}

src/cours/templates/cours/courses-list-sidebar.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}


{% block content %}

  <main>
    <section id="hero_in" class="courses">
      <div class="wrapper">
        <div class="container">
          <h1 class="fadeInUp"><span></span>Nos cours</h1>
        </div>
      </div>
    </section>
    <!--/hero_in-->

    <div class="filters_listing sticky_horizontal">
      <div class="container">
        <ul class="clearfix">
          <li>
            <div class="switch-field">
              <input type="radio" id="all" name="listing_filter" value="all" checked>
              <label for="all">Tout</label>
              <input type="radio" id="popular" name="listing_filter" value="popular">
              <label for="popular">Populaire</label>
              <input type="radio" id="latest" name="listing_filter" value="latest">
              <label for="latest">Récent</label>
            </div>
          </li>
          <li>
            <div class="layout_view">
              <a href="{% url 'courses-grid' %}"><i class="icon-th"></i></a>
              <a href="#0" class="active"><i class="icon-th-list"></i></a>
            </div>
          </li>
          <li>
            <select name="orderby" class="selectbox" onchange="location = this.value;">
              <option value="category">Categories</option>
              <option value="all">Tout</option>
              {% for categorie in categories %}
              <option value="{% url 'categorie-list' pk=categorie.pk %}">{{ categorie.nom }}</option>
              {% endfor %}
              </select>
          </li>
        </ul>
      </div>
      <!-- /container -->
    </div>
    <!-- /filters -->

    <div class="container margin_60_35">
      <div class="row">
        <aside class="col-lg-3" id="sidebar">
          <div id="filters_col"> <a data-toggle="collapse" href="#collapseFilters" aria-expanded="false" aria-controls="collapseFilters" id="filters_col_bt">Filtres </a>
            <div class="collapse show" id="collapseFilters">
              <div class="filter_type">
                <form method="POST" enctype="multipart/form-data" class="search-form">{% csrf_token %}
                    {% crispy form %}
                </form>
              </div>
            </div>
            <!--/collapse -->
          </div>
          <!--/filters col-->
        </aside>
        <!-- /aside -->

        <div class="col-lg-9" id="list_sidebar">
          <div class="row replace" style="display:flex;">
          {% for c in cours %}
            {% include 'cours/snippets/card-cours-list.html' with instance=c %}
          <!-- /box_list -->
          {% endfor %}
          </div>
          <!-- /box_list -->
          <p class="text-center add_top_60"><a href="#0" class="btn_1 rounded">Voir plus</a></p>
        </div>
        <!-- /col -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
    <div class="bg_color_1">
      <div class="container margin_60_35">
        <div class="row">
          <div class="col-md-4">
            <a href="#0" class="boxed_list">
              <i class="pe-7s-help2"></i>
              <h4>Need Help? Contact us</h4>
              <p>Cum appareat maiestatis interpretaris et, et sit.</p>
            </a>
          </div>
          <div class="col-md-4">
            <a href="#0" class="boxed_list">
              <i class="pe-7s-wallet"></i>
              <h4>Payments and Refunds</h4>
              <p>Qui ea nemore eruditi, magna prima possit eu mei.</p>
            </a>
          </div>
          <div class="col-md-4">
            <a href="#0" class="boxed_list">
              <i class="pe-7s-note2"></i>
              <h4>Quality Standards</h4>
              <p>Hinc vituperata sed ut, pro laudem nonumes ex.</p>
            </a>
          </div>
        </div>
        <!-- /row -->
      </div>
      <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
  </main>
  <!--/main-->

{% endblock %}

{% block javascript %}
<script>
$(function () {
    {% if anchor %}
        console.log("ancre repérée")
        $(document).ready(function(){
            window.location = '#{{ anchor }}'
        });
        $(document.body).animate({

            'scrollTop':   $('#{{ anchor }}').offset().top
        }, 2000);
    {% endif %}
});

  function display_facultes(){
            var universite_id = $('#id_universite :selected').val();
            $('#div_id_faculte').show()
            request_url = '/apprenants/get_faculte/' + universite_id + '/';
            $.ajax({
                  url: request_url,
                  success: function(json){
                    var strResult;
                    $('#div_id_faculte').empty();
                    strResult = '<label for="id_faculte" class="control-label">'+
                      'Faculté </label><br>'+
                      '<select name="faculte" class="select form-control" required="" id="id_faculte">'+
                      '<option value="" selected="">---------</option>'

                      for(var j = 0; j < json.length; j++){
                            strResult += '<option value="' + parseInt(json[j][0]) + '">' + json[j][1] +'</option>'
                        }
                        strResult += '</select>'
                        $('#div_id_faculte').append(strResult)
                  }
            })
  }

  if ($('#id_universite').value){
    display_facultes();
  }
  $('#id_universite').change(function() {
    display_facultes();
  });


  var searchForm = $(".search-form")
  var httpMethod = searchForm.attr("method");
  var actionEndpoint = '/cours/ajax-get-cours/';

  function ajax_display_cours() {
      var formData = searchForm.serialize();
      console.log(formData)
      $.ajax({
        url: actionEndpoint,
        method: httpMethod,
        data: formData,
        success: function(data){
            $('.replace').html(data.cours_html)
        },
        error: function(errorData){
          $.alert({
            title: "Oops!",
            content: "Une erreur s'est produite.",
            theme: "modern",
          })
        }
      })
    }

  searchForm.change(function() {
      ajax_display_cours()
  });
</script>


{% endblock %}